[project]
name = "8-fold-assistant"
version = "0.1.0"
description = "AI-powered 8-fold Assistant"
authors = [
    { name = "Jnanesh P S" }
]

requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.1",
    "streamlit>=1.51.0",
]

[project.scripts]
start = "app:main"

[tool.uv]
package = true
